CREATE TABLE field (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    width INT NOT NULL CHECK ( width > 0 ),
    height INT NOT NULL CHECK ( height > 0 ),
    UNIQUE (width, height)
);

CREATE TABLE path (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    field_id INT NOT NULL,
    color VARCHAR(20) NOT NULL,
    enemy_path PATH NOT NULL,
    FOREIGN KEY (field_id) REFERENCES field(id) ON DELETE CASCADE
);
