CREATE TABLE enemy (
    id UUID PRIMARY KEY DEFAULT uuidv7(),
    name VARCHAR(20) NOT NULL,
    max_health INT NOT NULL CHECK ( max_health > 0 ),
    move_speed NUMERIC(3, 2) NOT NULL CHECK ( move_speed > 0 ),
    evasion NUMERIC(3, 2) NOT NULL CHECK ( evasion >= 0.0 ),
    reward INT NOT NULL CHECK ( reward > 0 )
);

CREATE TABLE wave (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(20) NOT NULL,
    duration SMALLINT NOT NULL
);

CREATE TABLE spawn_group (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enemy_id UUID NOT NULL,
    count INT NOT NULL CHECK ( count > 0 ),
    UNIQUE (enemy_id, count),
    FOREIGN KEY (enemy_id) REFERENCES enemy(id) ON DELETE CASCADE
);

CREATE TABLE wave_spawn_group (
    index INT NOT NULL,
    wave_id INT NOT NULL,
    group_id INT NOT NULL,
    FOREIGN KEY (wave_id) REFERENCES wave(id) ON DELETE CASCADE,
    FOREIGN KEY (group_id) REFERENCES spawn_group(id) ON DELETE CASCADE,
    UNIQUE (index, wave_id)
);
