CREATE TABLE tower_type (
    id UUID PRIMARY KEY DEFAULT uuidv7(),
    name VARCHAR(20) NOT NULL
);

CREATE TABLE tower_level (
    level INT NOT NULL,
    tower_id UUID NOT NULL,
    cost INT NOT NULL CHECK ( cost > 0 ),
    damage NUMERIC(10, 2) NOT NULL CHECK ( damage > 0 ),
    range NUMERIC(10, 2) NOT NULL CHECK ( range > 0 ),
    fire_rate NUMERIC(10, 2) NOT NULL CHECK ( fire_rate > 0 ),
    PRIMARY KEY (level, tower_id),
    FOREIGN KEY (tower_id) REFERENCES tower_type(id) ON DELETE CASCADE
);

CREATE TABLE final_tower (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    path_id INT NOT NULL UNIQUE,
    damage NUMERIC(10, 2) NOT NULL CHECK ( damage > 0 ),
    range NUMERIC(10, 2) NOT NULL CHECK ( range > 0 ),
    fire_rate NUMERIC(10, 2) NOT NULL CHECK ( fire_rate > 0 ),
    x_pos INT NOT NULL,
    y_pos INT NOT NULL,
    FOREIGN KEY (path_id) REFERENCES path(id)
);
